### ISSUE TITLE
Should we have this script check .Redviron for proxy vars?

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/rstudio-server-controller#13]
Just tested with a new test user. Do you think we should have the script check for ~/.Renviron and put in the proxy info as needed so that package installs work? Or just provide set up instructions that include creating ~/.Renviron?

**Comment by HenrikBengtsson** [comment]
Stay tuned. I've got more updates coming, but the gist is:

* `rsc start` will launch a user-owned RStudio Server process on the current machine
* This works as-is on the development nodes
* To run on a compute node, the same should be done from an interactive job (Thus, no need to submit a special job script etc.)

So, the RStudio Server launcher `rsc` is invariant to running on a compute cluster or not.

Because of this, your question on setting `http_proxy` etc. so things work on the compute nodes, can be rephrased as "Should proxy env vars be set automatically in interactive jobs?".  (I think the answer should be "yes").

**Comment by HenrikBengtsson** [comment]
Moved to our internal C4 tracker.
